# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox, QStackedWidget
from TopsisScreen import Ui_TopsisScreen
from gui import Gui, Screen


class Ui_MainScreen(object):
    def __init__(self, MainScreen, gui: Gui):
        self.gui = gui
        self.checked_boxes = [] 
             
        # rzeczy wygenerowane przez Designer
        MainScreen.setObjectName("MainScreen")
        MainScreen.resize(783, 876)
        self.centralwidget = QtWidgets.QWidget(MainScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, 0, 801, 821))
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap("background.jpg"))
        self.background.setScaledContents(True)
        self.background.setObjectName("background")
        self.rsm = QtWidgets.QPushButton(self.centralwidget)
        self.rsm.setGeometry(QtCore.QRect(662, 630, 101, 28))
        self.rsm.setObjectName("rsm")
        self.tytul = QtWidgets.QLabel(self.centralwidget)
        self.tytul.setGeometry(QtCore.QRect(190, 450, 421, 61))
        self.tytul.setStyleSheet("border-color: rgb(159, 255, 124);")
        self.tytul.setFrameShape(QtWidgets.QFrame.Box)
        self.tytul.setObjectName("tytul")
        self.topsis = QtWidgets.QPushButton(self.centralwidget)
        self.topsis.setGeometry(QtCore.QRect(662, 590, 101, 28))
        self.topsis.setObjectName("topsis")
        self.topsis.clicked.connect(self.gotoTopsis)
        self.moc = QtWidgets.QCheckBox(self.centralwidget) 
        self.moc.setGeometry(QtCore.QRect(20, 690, 111, 20))
        self.moc.setStyleSheet("color: rgb(255, 255, 255);")
        self.moc.setObjectName("moc")
        self.moc.stateChanged.connect(lambda: self.update_checked_boxes(self.moc))   
        self.max_predk = QtWidgets.QCheckBox(self.centralwidget)
        self.max_predk.setGeometry(QtCore.QRect(20, 650, 171, 20))
        self.max_predk.setStyleSheet("color: rgb(255, 255, 255);")
        self.max_predk.setObjectName("max_predk")
        self.max_predk.stateChanged.connect(lambda: self.update_checked_boxes(self.max_predk))
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 560, 201, 41))
        self.label.setObjectName("label")
        self.pojemnosc = QtWidgets.QCheckBox(self.centralwidget)
        self.pojemnosc.setGeometry(QtCore.QRect(20, 770, 141, 20))
        self.pojemnosc.setStyleSheet("color: rgb(255, 255, 255);")
        self.pojemnosc.setObjectName("pojemnosc")
        self.pojemnosc.stateChanged.connect(lambda: self.update_checked_boxes(self.pojemnosc))
        self.masa = QtWidgets.QCheckBox(self.centralwidget)
        self.masa.setGeometry(QtCore.QRect(20, 730, 81, 20))
        self.masa.setStyleSheet("color: rgb(255, 255, 255);")
        self.masa.setObjectName("masa")
        self.masa.stateChanged.connect(lambda: self.update_checked_boxes(self.masa))
        self.uta = QtWidgets.QPushButton(self.centralwidget)
        self.uta.setGeometry(QtCore.QRect(662, 670, 101, 28))
        self.uta.setObjectName("uta")
        self.pokaz_baze = QtWidgets.QPushButton(self.centralwidget)
        self.pokaz_baze.setGeometry(QtCore.QRect(310, 760, 151, 28))
        self.pokaz_baze.setObjectName("pokaz_baze")
        self.przebieg = QtWidgets.QCheckBox(self.centralwidget)
        self.przebieg.setGeometry(QtCore.QRect(20, 610, 81, 20))
        self.przebieg.setStyleSheet("color: rgb(255, 255, 255);")
        self.przebieg.setObjectName("przebieg")
        self.przebieg.stateChanged.connect(lambda: self.update_checked_boxes(self.przebieg))
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(530, 560, 241, 20))
        self.label_3.setObjectName("label_3")
        self.safety_pr = QtWidgets.QPushButton(self.centralwidget)
        self.safety_pr.setGeometry(QtCore.QRect(660, 710, 101, 28))
        self.safety_pr.setObjectName("safety_pr")
        MainScreen.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainScreen)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 783, 26))
        self.menubar.setObjectName("menubar")
        MainScreen.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainScreen)
        self.statusbar.setObjectName("statusbar")
        MainScreen.setStatusBar(self.statusbar)

        self.retranslateUi(MainScreen)
        QtCore.QMetaObject.connectSlotsByName(MainScreen)

    def retranslateUi(self, MainScreen):
        _translate = QtCore.QCoreApplication.translate
        MainScreen.setWindowTitle(_translate("MainScreen", "MainScreen"))
        self.rsm.setText(_translate("MainScreen", "RSM"))
        self.tytul.setText(_translate("MainScreen", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600; color:#ffffff;\">SWD wyboru samochodu</span></p></body></html>"))
        self.topsis.setText(_translate("MainScreen", "Topsis"))
        self.moc.setText(_translate("MainScreen", "Moc silnika"))
        self.max_predk.setText(_translate("MainScreen", "Maksymalna prędkość"))
        self.label.setText(_translate("MainScreen", "<html><head/><body><p><span style=\" font-weight:600; color:#ffffff;\">Zaznacz interesujące kryteria:</span></p></body></html>"))
        self.pojemnosc.setText(_translate("MainScreen", "Pojemność baku"))
        self.masa.setText(_translate("MainScreen", "Masa"))
        self.uta.setText(_translate("MainScreen", "UTA"))
        self.pokaz_baze.setText(_translate("MainScreen", "Wyświetl całą bazę"))
        self.przebieg.setText(_translate("MainScreen", "Przebieg"))
        self.label_3.setText(_translate("MainScreen", "<html><head/><body><p><span style=\" font-weight:600; color:#ffffff;\">Wybierz metodę tworzenia rankingu:</span></p><p><br/></p></body></html>"))
        self.safety_pr.setText(_translate("MainScreen", "Safety principle"))

    def update_checked_boxes(self,checkbox):
        if checkbox.isChecked and checkbox.text() not in self.checked_boxes:
            self.checked_boxes.append(checkbox.text())
        else:
            self.checked_boxes.remove(checkbox.text())

    def _nothing_checked(self):
        if len(self.checked_boxes) < 2:
            msg = QMessageBox()
            msg.setText("Proszę wybrać przynajmniej 2 kryteria.")
            msg.setIcon(QMessageBox.Critical)
            msg.exec_()
            return False
        return True
    
    def gotoTopsis(self):
        flag = self._nothing_checked()
        if flag:
            self.gui.show_screen(Screen.TOPSIS)
    
    

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    widget = QStackedWidget()
    widget.setFixedHeight(876)
    widget.setFixedWidth(783)

    MainScreen = QtWidgets.QMainWindow()
    widget.addWidget(MainScreen)
    ui = Ui_MainScreen()
    ui.setupUi(MainScreen)
    widget.show()

    sys.exit(app.exec_())
