# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ranking_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RankingScreen(object):
    def __init__(self, RankingScreen,gui,method):
        self.gui = gui
        self.method = method
        RankingScreen.setObjectName("RankingScreen")
        RankingScreen.resize(759, 864)
        self.centralwidget = QtWidgets.QWidget(RankingScreen)
        self.centralwidget.setObjectName("centralwidget")
        
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, 0, 801, 881))
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap("kod\\gui\\background.jpg"))
        self.background.setScaledContents(True)
        self.background.setObjectName("label")
        
        self.tytul = QtWidgets.QLabel(self.centralwidget)
        self.tytul.setGeometry(QtCore.QRect(170, 390, 421, 61))
        self.tytul.setStyleSheet("border-color: rgb(159, 255, 124);")
        self.tytul.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tytul.setObjectName("tytul")
        
        self.menu = QtWidgets.QPushButton(self.centralwidget)
        self.menu.setGeometry(QtCore.QRect(30, 360, 111, 41))
        self.menu.setObjectName("menu")
        self.menu.clicked.connect(lambda: self.gui.show_main())
        
        self.method_type = QtWidgets.QLabel(self.centralwidget)
        self.method_type.setGeometry(QtCore.QRect(30, 480, 200, 16))
        self.method_type.setObjectName("method_type")
        self.method_type.setFont(QtGui.QFont("Arial",8))
        self.method_type.setStyleSheet("color: white;")
        self.method_type.setText(f"Przyszedłem z: {self.method}")
        
        RankingScreen.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RankingScreen)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 759, 26))
        self.menubar.setObjectName("menubar")
        RankingScreen.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RankingScreen)
        self.statusbar.setObjectName("statusbar")
        RankingScreen.setStatusBar(self.statusbar)

        self.retranslateUi(RankingScreen)
        QtCore.QMetaObject.connectSlotsByName(RankingScreen)

    def retranslateUi(self, RankingScreen):
        _translate = QtCore.QCoreApplication.translate
        RankingScreen.setWindowTitle(_translate("RankingScreen", "RankingScreen"))
        self.tytul.setText(_translate("RankingScreen", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:600; color:#ffffff;\">Ranking</span></p></body></html>"))
        self.menu.setText(_translate("RankingScreen", "Menu"))
    

